### ISSUE TITLE
Use this.field

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [sorinachirila/Java-Projects#1]
https://github.com/sorinachirila/Java-Projects/blob/c382e43d3a35967f6cc41179f4704b4f4b511893/JavaAdvanced_Homework1/src/encapsulation/User.java#L45

Fiindca esti in aceeasi clasa poti sa folosesti this.numelevariabilei in loc sa apelezi getter

**Comment by sorinachirila** [comment]
am modificat
