### ISSUE TITLE
Wrong logic

### ISSUE THREAD

**Issue by nicolaeabacioaiei** [sorinachirila/Java-Projects#2]
https://github.com/sorinachirila/Java-Projects/blob/c382e43d3a35967f6cc41179f4704b4f4b511893/JavaAdvanced_Homework2/src/cars/Vehicle.java#L42

Aici e practic un setter dar are alt nume. Cum zice si in cerinta vrem sa setam noua valoare, nu sa o adunam

**Comment by sorinachirila** [comment]
am corectat!
